application:
  # service 实现类
  service: tech.ides.rest.IdesServer
  # platform 生命周期相关类
  platformLifecycles:
    - tech.ides.datasource.DataSourceFactory
    - tech.ides.extension.ETPluginRegister
  serviceLifecycles:
    - tech.ides.rest.ControlHandlerHook

  # 数据库注册信息
  connectMetaData:
    - name: test
      format: jdbc
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
      driver: com.mysql.jdbc.Driver
      user: test
      password: test