application:
  # service 实现类
  service: tech.ides.rest.IdesServer
  # platform 生命周期相关类
  platformLifecycles:
    - tech.ides.datasource.DataSourceFactory
  serviceLifecycles:
    - tech.ides.rest.ControlHandlerHook